version: 0.2
phases:
 build:
   commands:
     - echo Entered build phase
     - mvn clean package
 post_build:
   commands:
     - echo Build completed sucessfully
artifacts:
   files:
      -target/empyyy.jar
   discard-paths: yes
